/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as etaCircuitVerifierSol from "./ETACircuitVerifier.sol";
export type { etaCircuitVerifierSol };
import type * as etaVerifierSol from "./ETAVerifier.sol";
export type { etaVerifierSol };
export type { ETAProver } from "./ETAProver";
