import { ethers } from "hardhat";

async function main() {
  // Deploy the ETACircuitVerifier first (generated by snarkjs)
  const ETACircuitVerifier = await ethers.getContractFactory("Groth16Verifier");
  const verifier = await ETACircuitVerifier.deploy();
  await verifier.waitForDeployment();
  console.log("ETACircuitVerifier deployed to:", await verifier.getAddress());

  // Deploy our main verifier contract
  const ZKETAVerifier = await ethers.getContractFactory("ZKETAVerifier");
  const zkVerifier = await ZKETAVerifier.deploy(await verifier.getAddress());
  await zkVerifier.waitForDeployment();
  console.log("ZKETAVerifier deployed to:", await zkVerifier.getAddress());
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});